# octocat/.github [another third repository]
# .github/workflows/mirror.yml
name: Mirror
on:
#   schedule:
#     - cron: "36 */6 * * *"
  workflow_dispatch:

    
jobs:
  mirror_pastell:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://gitlab.adullact.net/Libriciel/pastell/pastell.git .
      - run: git push --mirror "https://x:$GITHUB_TOKEN@github.com/syji35/pastell.git"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          
  mirror_parapheur:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://gitlab.adullact.net/Libriciel/i-Parapheur/iparapheur5/ip-compose.git .
      - run: git push --mirror "https://x:$GITHUB_TOKEN@github.com/megalis-bretagne/parapheur-v5.git"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
